package com.vcoding.common.response;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {
    SUCCESS("SUCCESS", "成功", 200),
    COMMON_BAD_REQUEST("COMMON_BAD_REQUEST", "请求参数错误", 400),
    COMMON_UNAUTHORIZED("COMMON_UNAUTHORIZED", "未登录", 401),
    COMMON_FORBIDDEN("COMMON_FORBIDDEN", "无权限访问", 403),
    COMMON_NOT_FOUND("COMMON_NOT_FOUND", "资源不存在", 404),
    COMMON_INTERNAL_ERROR("COMMON_INTERNAL_ERROR", "系统异常", 500),
    AUTH_INVALID_TOKEN("AUTH_INVALID_TOKEN", "登录状态无效", 401),
    AUTH_TOKEN_EXPIRED("AUTH_TOKEN_EXPIRED", "登录已过期", 401),
    AUTH_INVALID_IMAGE_CAPTCHA("AUTH_INVALID_IMAGE_CAPTCHA", "图形验证码错误", 400),
    AUTH_IMAGE_CAPTCHA_EXPIRED("AUTH_IMAGE_CAPTCHA_EXPIRED", "图形验证码已过期", 400),
    AUTH_INVALID_USERNAME_OR_PASSWORD("AUTH_INVALID_USERNAME_OR_PASSWORD", "用户名或密码错误", 400),
    AUTH_INVALID_SMS_CODE("AUTH_INVALID_SMS_CODE", "验证码错误", 400),
    AUTH_SMS_CODE_EXPIRED("AUTH_SMS_CODE_EXPIRED", "验证码已过期", 400),
    AUTH_SMS_SEND_COOLDOWN("AUTH_SMS_SEND_COOLDOWN", "短信验证码发送过于频繁", 429),
    AUTH_SMS_SEND_LIMIT_EXCEEDED("AUTH_SMS_SEND_LIMIT_EXCEEDED", "短信验证码发送次数已达上限", 429),
    AUTH_SMS_VERIFY_LIMIT_EXCEEDED("AUTH_SMS_VERIFY_LIMIT_EXCEEDED", "验证码校验失败次数已达上限", 429),
    AUTH_UNSUPPORTED_SMS_SCENE("AUTH_UNSUPPORTED_SMS_SCENE", "不支持的短信验证码场景", 400),
    AUTH_USERNAME_ALREADY_EXISTS("AUTH_USERNAME_ALREADY_EXISTS", "用户名已存在", 400),
    AUTH_PHONE_ALREADY_EXISTS("AUTH_PHONE_ALREADY_EXISTS", "手机号已注册", 400),
    AUTH_INVALID_PASSWORD_HASH("AUTH_INVALID_PASSWORD_HASH", "密码凭证格式错误", 500),
    AUTH_USER_DISABLED("AUTH_USER_DISABLED", "用户已禁用", 403),
    AUTH_NOT_LOGIN("AUTH_NOT_LOGIN", "用户未登录", 401);

    private final String code;
    private final String message;
    private final int httpStatus;
}
