#!/usr/bin/env bash
set -euo pipefail

failures=0

check_path() {
  local path="$1"
  if [[ ! -e "$path" ]]; then
    echo "缺少: $path"
    failures=$((failures + 1))
  fi
}

check_contains() {
  local file="$1"
  local text="$2"
  if [[ ! -f "$file" ]]; then
    echo "缺少: $file"
    failures=$((failures + 1))
    return
  fi

  if ! grep -Fq -- "$text" "$file"; then
    echo "内容缺失: $file -> $text"
    failures=$((failures + 1))
  fi
}

required_paths=(
  "AGENTS.md"
  "README.md"
  "docs/architecture/technology-and-architecture.md"
  "docs/design/visual-guidelines.md"
  "frontend/package.json"
  "frontend/pnpm-workspace.yaml"
  "frontend/apps/auth-web/package.json"
  "frontend/apps/auth-web/src/main.ts"
  "frontend/apps/auth-web/src/components/AuthBrandStage.vue"
  "frontend/apps/auth-web/src/components/AuthCard.vue"
  "frontend/apps/auth-web/src/components/CaptchaVerifyDialog.vue"
  "frontend/apps/auth-web/src/components/AuthLoginForm.vue"
  "frontend/apps/auth-web/src/components/AuthRegisterForm.vue"
  "frontend/apps/auth-web/src/router/index.ts"
  "frontend/apps/auth-web/src/types/auth.ts"
  "frontend/apps/auth-web/src/views/HomeView.vue"
  "frontend/apps/portal-web/package.json"
  "frontend/apps/portal-web/src/main.ts"
  "frontend/apps/portal-web/src/router/index.ts"
  "frontend/apps/demo-system-web/package.json"
  "frontend/apps/demo-system-web/src/main.ts"
  "frontend/apps/demo-system-web/src/router/guards.ts"
  "frontend/apps/demo-system-web/src/router/index.ts"
  "frontend/apps/demo-system-web/src/stores/auth.ts"
  "frontend/packages/ui/src/index.ts"
  "frontend/packages/ui/src/overlay/context.ts"
  "frontend/packages/ui/src/overlay/errors.ts"
  "frontend/packages/ui/src/overlay/index.ts"
  "frontend/packages/ui/src/overlay/openOverlay.ts"
  "frontend/packages/ui/src/overlay/types.ts"
  "frontend/packages/ui/src/styles/tokens.css"
  "frontend/packages/ui/src/styles/base.css"
  "frontend/packages/ui/src/styles/element.css"
  "frontend/packages/ui/src/styles/components.css"
  "frontend/packages/ui/src/styles/index.css"
  "frontend/packages/auth-client/package.json"
  "frontend/packages/auth-client/src/api/auth.ts"
  "frontend/packages/auth-client/src/api/captcha.ts"
  "frontend/packages/auth-client/src/api/index.ts"
  "frontend/packages/auth-client/src/api/password.ts"
  "frontend/packages/auth-client/src/api/sms.ts"
  "frontend/packages/auth-client/src/crypto/index.ts"
  "frontend/packages/auth-client/src/crypto/password.ts"
  "frontend/packages/auth-client/src/index.ts"
  "frontend/packages/auth-client/src/request/http.ts"
  "frontend/packages/auth-client/src/request/index.ts"
  "frontend/packages/auth-client/src/types/auth.ts"
  "frontend/packages/auth-client/src/types/captcha.ts"
  "frontend/packages/auth-client/src/types/http.ts"
  "frontend/packages/auth-client/src/types/index.ts"
  "frontend/packages/auth-client/src/types/password.ts"
  "frontend/packages/auth-client/src/types/sms.ts"
  "frontend/packages/shared/src/index.ts"
  "backend/pom.xml"
  "backend/vcoding-common/pom.xml"
  "backend/vcoding-common/src/main/java/com/vcoding/common/response/ApiResponse.java"
  "backend/vcoding-common/src/main/java/com/vcoding/common/response/ErrorCode.java"
  "backend/vcoding-common/src/main/java/com/vcoding/common/exception/BusinessException.java"
  "backend/vcoding-common/src/main/java/com/vcoding/common/exception/GlobalExceptionHandler.java"
  "backend/vcoding-common/src/main/java/com/vcoding/common/auth/AuthContext.java"
  "backend/vcoding-common/src/main/java/com/vcoding/common/auth/AuthHeaderNames.java"
  "backend/vcoding-common/src/main/java/com/vcoding/common/auth/CookieTokenResolver.java"
  "backend/vcoding-common/src/main/java/com/vcoding/common/auth/CurrentUser.java"
  "backend/vcoding-common/src/main/java/com/vcoding/common/auth/GatewayUserHeaderService.java"
  "backend/vcoding-common/src/main/java/com/vcoding/common/auth/InternalGatewayUserFilter.java"
  "backend/vcoding-common/src/main/java/com/vcoding/common/auth/JwtService.java"
  "backend/vcoding-common/src/main/java/com/vcoding/common/auth/config/GatewayInternalProperties.java"
  "backend/vcoding-common/src/main/java/com/vcoding/common/auth/config/VcodingAuthProperties.java"
  "backend/vcoding-common/src/main/java/com/vcoding/common/trace/TraceIdHolder.java"
  "backend/vcoding-common/src/main/java/com/vcoding/common/trace/TraceIdFilter.java"
  "backend/vcoding-auth/pom.xml"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/VcodingAuthApplication.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/CaptchaController.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/AuthAccountController.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/HealthController.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/dto/CurrentUserResponse.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/dto/RegisterRequest.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/dto/RegisterResponse.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/dto/LoginRequest.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/dto/LoginResponse.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/dto/PasswordPublicKeyResponse.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/dto/SmsLoginRequest.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/application/captcha/ImageCaptchaService.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/application/captcha/SmsCodeService.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/application/crypto/PasswordCryptoService.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/application/session/AuthSessionService.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/application/user/PasswordHashService.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/application/user/UserRegisterService.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/config/OpenApiConfig.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/domain/sms/SmsScene.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/domain/sms/SmsSender.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/domain/user/UserStatus.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/infrastructure/sms/ConsoleSmsSender.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/infrastructure/persistence/entity/UserEntity.java"
  "backend/vcoding-auth/src/main/java/com/vcoding/auth/infrastructure/persistence/mapper/UserMapper.java"
  "backend/vcoding-auth/src/main/resources/db/migration/V1__init_user_center.sql"
  "backend/vcoding-auth/src/main/resources/application.yml"
  "backend/vcoding-auth/src/main/resources/application-local.yml"
  "backend/vcoding-gateway/pom.xml"
  "backend/vcoding-gateway/src/main/java/com/vcoding/gateway/VcodingGatewayApplication.java"
  "backend/vcoding-gateway/src/main/java/com/vcoding/gateway/filter/GatewayAuthenticationFilter.java"
  "backend/vcoding-gateway/src/main/resources/application.yml"
  "backend/vcoding-system-demo/pom.xml"
  "backend/vcoding-system-demo/src/main/java/com/vcoding/system/demo/VcodingSystemDemoApplication.java"
  "backend/vcoding-system-demo/src/main/java/com/vcoding/system/demo/api/DemoProfileController.java"
  "backend/vcoding-system-demo/src/main/java/com/vcoding/system/demo/api/dto/DemoProfileResponse.java"
  "backend/vcoding-system-demo/src/main/java/com/vcoding/system/demo/config/InternalGatewayAuthConfig.java"
  "backend/vcoding-system-demo/src/main/resources/application.yml"
  "deploy/local/docker-compose.yml"
)

for path in "${required_paths[@]}"; do
  check_path "$path"
done

check_contains "frontend/pnpm-workspace.yaml" "apps/*"
check_contains "frontend/pnpm-workspace.yaml" "packages/*"
check_contains "AGENTS.md" "docs/design/visual-guidelines.md"
check_contains "docs/architecture/technology-and-architecture.md" "docs/design/visual-guidelines.md"
check_contains "docs/design/visual-guidelines.md" "开发者工具风格"
check_contains "docs/design/visual-guidelines.md" "--vc-primary"
check_contains "frontend/apps/auth-web/package.json" "vite"
check_contains "frontend/apps/auth-web/package.json" "vue"
check_contains "frontend/apps/auth-web/src/main.ts" "@vcoding/ui/styles"
check_contains "frontend/apps/auth-web/src/views/HomeView.vue" "AuthCard"
check_contains "frontend/apps/auth-web/src/components/AuthCard.vue" "Transition"
check_contains "frontend/apps/auth-web/src/components/AuthCard.vue" "openOverlay"
check_contains "frontend/apps/auth-web/src/components/AuthCard.vue" "loginByPassword"
check_contains "frontend/apps/auth-web/src/components/AuthCard.vue" "loginBySmsCode"
check_contains "frontend/apps/auth-web/src/components/AuthCard.vue" "register("
check_contains "frontend/apps/auth-web/src/components/AuthCard.vue" "VITE_DEFAULT_LOGIN_REDIRECT"
check_contains "frontend/apps/auth-web/src/components/AuthCard.vue" "VITE_ALLOWED_REDIRECT_ORIGINS"
check_contains "frontend/apps/auth-web/src/components/AuthLoginForm.vue" "短信登录"
check_contains "frontend/apps/auth-web/src/components/AuthRegisterForm.vue" "创建账号"
check_contains "frontend/apps/auth-web/src/components/CaptchaVerifyDialog.vue" "useOverlay"
check_contains "frontend/apps/portal-web/package.json" "pinia"
check_contains "frontend/apps/portal-web/src/main.ts" "@vcoding/ui/styles"
check_contains "frontend/apps/demo-system-web/package.json" "vue-router"
check_contains "frontend/apps/demo-system-web/src/main.ts" "@vcoding/ui/styles"
check_contains "frontend/apps/demo-system-web/src/router/guards.ts" "getCurrentUser"
check_contains "frontend/apps/demo-system-web/src/router/guards.ts" "VITE_AUTH_WEB_URL"
check_contains "frontend/apps/demo-system-web/src/router/guards.ts" "redirect"
check_contains "frontend/packages/auth-client/package.json" "typescript"
check_contains "frontend/packages/auth-client/src/index.ts" "export * from './api'"
check_contains "frontend/packages/auth-client/src/index.ts" "export * from './types'"
check_contains "frontend/packages/auth-client/src/request/http.ts" "interceptors.request"
check_contains "frontend/packages/auth-client/src/request/http.ts" "interceptors.response"
check_contains "frontend/packages/auth-client/src/request/http.ts" "SUCCESS_CODE = 0"
check_contains "frontend/packages/auth-client/src/request/http.ts" "withCredentials: true"
check_contains "frontend/packages/auth-client/src/api/auth.ts" "/auth/login"
check_contains "frontend/packages/auth-client/src/api/auth.ts" "/auth/login/sms"
check_contains "frontend/packages/auth-client/src/api/auth.ts" "/auth/register"
check_contains "frontend/packages/auth-client/src/api/auth.ts" "/auth/me"
check_contains "frontend/packages/auth-client/src/api/auth.ts" "/auth/logout"
check_contains "frontend/packages/auth-client/src/api/password.ts" "/auth/password/public-key"
check_contains "frontend/packages/auth-client/src/api/captcha.ts" "/auth/captcha/image"
check_contains "frontend/packages/auth-client/src/api/sms.ts" "/auth/sms/send"
check_contains "frontend/packages/auth-client/src/types/index.ts" "export * from './auth'"
check_contains "frontend/packages/auth-client/src/crypto/password.ts" "RSA-OAEP"
check_contains "frontend/packages/auth-client/src/crypto/password.ts" "passwordCiphertext"
check_contains "frontend/packages/ui/package.json" "\"./styles\""
check_contains "frontend/packages/ui/package.json" "\"./overlay\""
check_contains "frontend/packages/ui/src/index.ts" "openOverlay"
check_contains "frontend/packages/ui/src/overlay/openOverlay.ts" "provide(overlayControllerKey"
check_contains "frontend/packages/ui/src/overlay/openOverlay.ts" "options.render(controller)"
check_contains "frontend/packages/ui/src/overlay/context.ts" "useOverlay"
check_contains "frontend/apps/auth-web/src/main.ts" "VcodingOverlayPlugin"
check_contains "frontend/packages/ui/src/styles/tokens.css" "--vc-primary"
check_contains "frontend/packages/ui/src/styles/components.css" ".vc-tech-grid-bg"
check_contains "frontend/packages/ui/src/styles/element.css" "--el-color-primary"
check_contains "docs/design/visual-guidelines.md" "frontend/packages/ui/src/styles"
check_contains "backend/pom.xml" "spring-boot-dependencies"
check_contains "backend/pom.xml" "spring-cloud-dependencies"
check_contains "backend/pom.xml" "mybatis-plus-spring-boot3-starter"
check_contains "backend/vcoding-common/src/main/java/com/vcoding/common/response/ApiResponse.java" "traceId"
check_contains "backend/vcoding-common/src/main/java/com/vcoding/common/response/ApiResponse.java" "SUCCESS_CODE = 0"
check_contains "backend/vcoding-common/src/main/java/com/vcoding/common/exception/GlobalExceptionHandler.java" "@RestControllerAdvice"
check_contains "backend/vcoding-common/pom.xml" "jjwt-api"
check_contains "backend/vcoding-common/src/main/java/com/vcoding/common/auth/JwtService.java" "Jwts.builder"
check_contains "backend/vcoding-common/src/main/java/com/vcoding/common/auth/AuthContext.java" "requireLogin"
check_contains "backend/vcoding-common/src/main/java/com/vcoding/common/auth/GatewayUserHeaderService.java" "HmacSHA256"
check_contains "backend/vcoding-common/src/main/java/com/vcoding/common/auth/InternalGatewayUserFilter.java" "verifyAndParse"
check_contains "backend/vcoding-common/src/main/java/com/vcoding/common/trace/TraceIdHolder.java" "X-Trace-Id"
check_contains "backend/vcoding-auth/pom.xml" "spring-boot-starter-web"
check_contains "backend/vcoding-auth/pom.xml" "spring-boot-starter-data-redis"
check_contains "backend/vcoding-auth/pom.xml" "springdoc-openapi-starter-webmvc-ui"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/VcodingAuthApplication.java" "scanBasePackages = \"com.vcoding\""
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/config/OpenApiConfig.java" "vcoding 统一用户中心接口"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/CaptchaController.java" "/captcha/image"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/CaptchaController.java" "/sms/send"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/AuthAccountController.java" "/register"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/AuthAccountController.java" "/login"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/AuthAccountController.java" "/login/sms"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/AuthAccountController.java" "/password/public-key"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/AuthAccountController.java" "/me"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/AuthAccountController.java" "/logout"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/dto/LoginRequest.java" "passwordCiphertext"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/dto/RegisterRequest.java" "passwordCiphertext"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/application/crypto/PasswordCryptoService.java" "RSA/ECB/OAEPWithSHA-256AndMGF1Padding"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/application/session/AuthSessionService.java" "JwtService"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/application/session/AuthSessionService.java" "HttpOnly Cookie"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/application/session/AuthSessionService.java" "SmsScene.LOGIN"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/application/user/PasswordHashService.java" "PBKDF2WithHmacSHA256"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/application/user/UserRegisterService.java" "SmsScene.REGISTER"
check_contains "backend/vcoding-auth/src/main/resources/db/migration/V1__init_user_center.sql" "CREATE TABLE uc_user"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/application/captcha/ImageCaptchaService.java" "captcha:image:"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/application/captcha/SmsCodeService.java" "captcha:sms:"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/infrastructure/sms/ConsoleSmsSender.java" "ConsoleSmsSender"
check_contains "backend/vcoding-auth/src/main/java/com/vcoding/auth/api/HealthController.java" "/health"
check_contains "backend/vcoding-gateway/pom.xml" "spring-cloud-starter-gateway"
check_contains "backend/vcoding-gateway/src/main/java/com/vcoding/gateway/filter/GatewayAuthenticationFilter.java" "GlobalFilter"
check_contains "backend/vcoding-gateway/src/main/resources/application.yml" "Path=/api/demo/**"
check_contains "backend/vcoding-system-demo/src/main/java/com/vcoding/system/demo/config/InternalGatewayAuthConfig.java" "InternalGatewayUserFilter"
check_contains "backend/vcoding-system-demo/src/main/java/com/vcoding/system/demo/api/DemoProfileController.java" "/profile"
check_contains "deploy/local/docker-compose.yml" "mysql"
check_contains "deploy/local/docker-compose.yml" "redis"
check_contains "README.md" "docker compose -f deploy/local/docker-compose.yml up -d"
check_contains "README.md" "vcoding-gateway: localhost:8080"

while IFS= read -r vue_file; do
  line_count=$(wc -l < "$vue_file" | tr -d ' ')
  if [[ "$line_count" -gt 800 ]]; then
    echo "Vue 文件超过 800 行: $vue_file (${line_count} 行)"
    failures=$((failures + 1))
  fi
done < <(find frontend -path "*/node_modules/*" -prune -o -path "*/dist/*" -prune -o -name "*.vue" -type f -print)

if [[ "$failures" -gt 0 ]]; then
  echo "结构验证失败: ${failures} 项问题"
  exit 1
fi

echo "结构验证通过"
