spring:
  datasource:
    url: ${VCODING_DB_URL}
    username: ${VCODING_DB_USERNAME}
    password: ${VCODING_DB_PASSWORD}
  data:
    redis:
      host: ${VCODING_REDIS_HOST}
      port: ${VCODING_REDIS_PORT:6379}
      password: ${VCODING_REDIS_PASSWORD:}
  flyway:
    enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

vcoding:
  auth:
    cookie-secure: true
    jwt-secret: ${VCODING_JWT_SECRET}
